- name: Playbook
  hosts: localhost
  tasks:
    - name: Add bitnami Helm repository
      command: helm repo add bitnami https://charts.bitnami.com/bitnami
      ignore_errors: yes  # Ignore errors in case the repo is already added

    - name: Deploy latest version of Redis chart inside polymetrie namespace (and create it)
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        release_namespace: test
        create_namespace: true

    - name: Deploy postgres chart inside polymetrie namespace (and create it)
      kubernetes.core.helm:
        name: postgres
        chart_ref: bitnami/postgresql
        release_namespace: test
        create_namespace: true
        values:
          postgresqlDatabase: polymetrie
          postgresqlUsername: polymetrie
          postgresqlPassword: polymetrie

