global:
  storageClass: ""
  postgresql:
    auth:
      postgresPassword: "dev_password"
      username: "postgres"
      password: "dev_password"
      database: "postgres"
auth:
  ## @param auth.enablePostgresUser Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
  ##
  enablePostgresUser: true
  ## @param auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` is provided
  ##
  postgresPassword: "dev_password"
  ## @param auth.username Name for a custom user to create
  ##
  username: "postgres"
  ## @param auth.password Password for the custom user to create. Ignored if `auth.existingSecret` is provided
  ##
  password: "dev_password"
  ## @param auth.database Name for a custom database to create
  ##
  database: "postgres"


primary:
  name: primary
  pgHbaConfiguration: |-
    host all all all trust