apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-stack
  name: polymetrie-sm
  namespace: default
spec:
  endpoints:
  - interval: 30s
    targetPort: 5000
    path: /metrics
  namespaceSelector:
    matchNames:
      default
  selector:
    matchLabels:
      app: polymetrie
      release: prometheus-stack