- name: Deploy latest version of postgresql chart inside monitoring namespace (and create it)
  kubernetes.core.helm:
    name: postgresql
    chart_ref: bitnami/postgresql
    release_namespace: polymetrie
    create_namespace: true