- name: Install PostgreSQL and Redis using Helm
  hosts: localhost
  gather_facts: false
  vars:
    postgresql_password: "postgres"
    redis_password: "redis"
  tasks:
    - name: Add Helm repository for PostgreSQL
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Install PostgreSQL using Helm with password override
      community.kubernetes.helm:
        name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: polymetrie
        create_namespace: true
        wait: true
        values:
          postgresqlPassword: "{{ postgresql_password }}"

    - name: Add Helm repository for Redis
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Install Redis using Helm with password override
      community.kubernetes.helm:
        name: redis
        chart_ref: bitnami/redis
        release_namespace: polymetrie
        create_namespace: true
        wait: true
        values:
          auth.password: "{{ redis_password }}"



